/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/codeMeter/scene.gltf 
Author: dreamerinthefalls (https://sketchfab.com/dreamerinthefalls)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/code-meter-a877896991064296a66d461a8e62e62b
Title: CODE METER
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const CodeMeter = (props) => {
  const { nodes, materials } = useGLTF('models/codeMeter/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.16, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-1.105, 30.666, 0.032]} rotation={[Math.PI, 1.245, -Math.PI]}>
          <mesh geometry={nodes['Cylinder_3_Metal_-_Gold_0'].geometry} material={materials['Metal_-_Gold']} />
          <mesh geometry={nodes['Cylinder_3_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} />
        </group>
        <group position={[-1.105, -30.388, 0.032]}>
          <mesh geometry={nodes['Cylinder_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} />
          <mesh geometry={nodes['Cylinder_Metal_-_Gold_0'].geometry} material={materials['Metal_-_Gold']} />
        </group>
        <mesh geometry={nodes['Disc_2_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[-1.742, -61.055, -0.159]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes['Disc_1_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[-1.742, -46.089, -0.159]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes['Disc_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[-1.437, 44.229, 1.186]} />
        <mesh geometry={nodes.Tube_7_Mat_0.geometry} material={materials.material} position={[-1.105, -44.652, 0.032]} />
        <mesh geometry={nodes.Tube_6_Mat1_0.geometry} material={materials['Mat.1']} position={[-1.105, 42.779, 0.032]} />
        <mesh geometry={nodes['Cylinder_12_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[16.329, -1.345, -12.199]} />
        <mesh geometry={nodes['Cylinder_11_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[5.825, 0.743, -20.687]} />
        <mesh geometry={nodes['Cylinder_10_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[-8.34, -1.345, -20.387]} />
        <mesh geometry={nodes['Cylinder_9_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[-18.741, -1.252, -12.366]} />
        <mesh geometry={nodes['Cylinder_8_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[-18.503, -1.252, 12.813]} />
        <mesh geometry={nodes['Cylinder_7_Metal_-_Gold_Antique_0'].geometry} material={materials['Metal_-_Gold_Antique']} position={[-7.403, 0.373, 20.598]} />
        <mesh geometry={nodes.Cylinder_6_Mat2_0.geometry} material={materials['Mat.2']} position={[5.956, 0.373, 20.598]} />
        <mesh geometry={nodes.Cylinder_5_Mat_0.geometry} material={materials.Mat_0} position={[20.364, 0.373, -0.796]} />
        <mesh geometry={nodes.Cylinder_4_Mat4_0.geometry} material={materials['Mat.4']} position={[16.67, 0.373, 12.069]} />
        <mesh geometry={nodes['Cylinder_2_Metal_-_Gold_0'].geometry} material={materials['Metal_-_Gold']} position={[-1.105, 11.404, 0.032]} />
        <mesh geometry={nodes['Cylinder_1_Metal_-_Gold_0'].geometry} material={materials['Metal_-_Gold']} position={[-1.105, -8.401, 0.032]} rotation={[Math.PI, -0.656, Math.PI]} />
        <mesh geometry={nodes.Tube_5_Mat5_0.geometry} material={materials['Mat.5']} position={[-1.105, -19.099, 0.032]} />
        <mesh geometry={nodes.Tube_4_Mat6_0.geometry} material={materials['Mat.6']} position={[-1.105, 1.4, 0.032]} />
        <mesh geometry={nodes.Tube_3_Mat7_0.geometry} material={materials['Mat.7']} position={[-1.105, 20.876, 0.032]} />
        <mesh geometry={nodes.Tube_2_Mat8_0.geometry} material={materials['Mat.8']} position={[-1.105, 39.087, 0.032]} />
        <mesh geometry={nodes.Tube_1_Mat9_0.geometry} material={materials['Mat.9']} position={[-1.105, -40.713, 0.032]} />
      </group>
    </group>
  )
}

useGLTF.preload('models/codeMeter/scene.gltf');

export default CodeMeter;
